# Generated by Django 5.0.8 on 2024-08-10 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=250)),
                ('apellidos', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=250)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_de_inicio', models.DateField()),
                ('fecha_de_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cooperante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=250)),
                ('apellidos', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=250)),
                ('carrera', models.CharField(max_length=250)),
                ('año_de_ingreso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PostulacionBeca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=250)),
                ('apellidos', models.CharField(max_length=250)),
                ('provincia', models.CharField(max_length=250)),
                ('canton', models.CharField(max_length=250)),
                ('parroquia', models.CharField(max_length=250)),
                ('comunidad', models.CharField(max_length=250)),
                ('cedula', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=250)),
                ('carrera', models.CharField(max_length=250)),
                ('aceptacion_de_cupo', models.FileField(blank=True, null=True, upload_to='aceptacion_cupos')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('apellidos', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionDeBeca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_de_asignacion', models.DateField()),
                ('beca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Sistema.beca')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Sistema.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadDeVoluntariado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actividad', models.CharField(max_length=250)),
                ('fecha', models.DateField()),
                ('horas', models.IntegerField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Sistema.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialAcademico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semestre', models.CharField(max_length=250)),
                ('comentarios', models.TextField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Sistema.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_de_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Sistema.beca')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Sistema.estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Sistema.universidad'),
        ),
    ]
