# Generated by Django 5.0.8 on 2025-01-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0002_alter_postulacionbeca_aceptacion_de_cupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacionbeca',
            name='aceptacion_de_cupo',
            field=models.FileField(blank=True, null=True, upload_to='Documentos'),
        ),
    ]
