# Generated by Django 5.0.8 on 2025-01-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0004_alter_postulacionbeca_aceptacion_de_cupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='estado',
            field=models.CharField(default='default_value', max_length=250),
            preserve_default=False,
        ),
    ]
