# Generated by Django 5.0.8 on 2025-01-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0005_estudiante_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacionbeca',
            name='aceptacion_de_cupo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
