# Generated by Django 5.0.8 on 2025-01-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0008_alter_postulacionbeca_aceptacion_de_cupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividaddevoluntariado',
            name='horas',
            field=models.CharField(max_length=250),
        ),
    ]
