# Generated by Django 5.0.8 on 2025-01-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0010_historialacademico_universidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialacademico',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='historialacademico',
            name='campus',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='historialacademico',
            name='residencia',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
