# Generated by Django 5.0.8 on 2025-01-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0011_remove_historialacademico_comentarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialacademico',
            name='campus',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
