# Generated by Django 5.0.8 on 2025-01-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0012_alter_historialacademico_campus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsignacionDeBeca',
        ),
    ]
