# Generated by Django 5.0.8 on 2025-01-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sistema', '0013_delete_asignaciondebeca'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
